---
title: "Hw2 -Genetic variances"
author: "Erika Sanchez"
date: "3/31/2020"
output: html_document
---

## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```

## Experimental design

Population 1

Variables: 
 - Plant yield (g/plant)
 - Cob Weight (g)
 - Leaf width (cm)

Environments:
 - Homestead, FL (2002)
 - Raleigh, NC (2003)
 - Columbia, MO 
 - Madison, WI
 

## Data
### Flint-Garcia et al., 2009 data

```{r}
f <- read.delim("data/journal.pone.0007433.s001.txt", header=TRUE)
str(f)
# Convert missing data to NA
f[f=="."] <- NA  


# four environments in population 1
table(f$Env)

f$INBRED <- as.factor(f$INBRED)
f$Env <- as.factor(f$Env)


# Trait 1: Yield
## This trait was evaluated in two environments: North Carolina (03N) and Missouri (03M)
# Inbred
# check data
f$PltYield_Inbred
class(f$PltYield_Inbred)
   # hist(as.numeric(f$PltYield_Inbred))
   # as.numeric(as.character(f$PltYield_Inbred))
hist(as.numeric(as.character(f$PltYield_Inbred)))

# tricky part, be careful:
f$PltYield_Inbred  <- as.numeric(as.character((f$PltYield_Inbred)))
fit_YInb <- lm(PltYield_Inbred ~ INBRED + Env, data=f) # fit linear model data= dataframe

summary(fit_YInb)
plot(fit_YInb)
anova(fit_YInb)

# Hybrid
# check data
f$PltYield_Hyb
class(f$PltYield_Hyb)
hist(as.numeric(as.character(f$PltYield_Hyb)))

f$PltYield_Hyb  <- as.numeric(as.character((f$PltYield_Hyb)))
fit_YHyb <- lm(PltYield_Hyb ~ INBRED + Env, data=f) 

summary(fit_YHyb)
plot(fit_YHyb)
anova(fit_YHyb)

# Trait 2: Cob Weight
# Inbred
# check data
f$CobWt_Inbred
class(f$CobWt_Inbred)
hist(as.numeric(as.character(f$CobWt_Inbred)))

f$CobWt_Inbred  <- as.numeric(as.character((f$CobWt_Inbred)))
fit_CobInb <- lm(CobWt_Inbred ~ INBRED + Env, data=f)

summary(fit_CobInb)
plot(fit_CobInb)
anova(fit_CobInb)

# Hybrid
# check data
f$CobWt_Hyb
class(f$CobWt_Hyb)
hist(as.numeric(as.character(f$CobWt_Hyb)))

f$CobWt_Hyb  <- as.numeric(as.character((f$CobWt_Hyb)))
fit_CHyb <- lm(CobWt_Hyb ~ INBRED + Env, data=f) 

summary(fit_CHyb)
plot(fit_CHyb)
anova(fit_CHyb)


# Trait 3: Leaf width
# Inbred
# check data
f$LFWDT_Inbred
class(f$LFWDT_Inbred)
hist(as.numeric(as.character(f$LFWDT_Inbred)))

f$LFWDT_Inbred  <- as.numeric(as.character((f$LFWDT_Inbred)))
fit_LFInb <- lm(LFWDT_Inbred ~ INBRED + Env, data=f)

summary(fit_LFInb)
plot(fit_LFInb)
anova(fit_LFInb)

# Hybrid
# check data
f$LFWDT_Hyb
class(f$LFWDT_Hyb)
hist(as.numeric(as.character(f$LFWDT_Hyb)))

f$LFWDT_Hyb  <- as.numeric(as.character((f$LFWDT_Hyb)))
fit_LHyb <- lm(LFWDT_Hyb ~ INBRED + Env, data=f) 

summary(fit_LHyb)
plot(fit_LHyb)
anova(fit_LHyb)


```

$$
H^2 = \frac{V_G}{V_G + V_E}
$$
With $(V_G =  MS(G) - MS(error)/e$ 


```{r}
# Heritabilities

## Yield

### Inbred
Va_YI =  (549.08 - 358.99)/2
Ve_YI = 358.99
H2_YI = Va_YI/(Va_YI + Ve_YI)

### Hybrid
Vg_Yh =  (2332 - 1210)/2
Ve_Yh = 1210
H2_Yh = Vg_Yh/(Vg_Yh + Ve_Yh)


## Cob Weigth

### Inbred
Va_CI =  (48.15 - 14.05)/4
Ve_CI = 14.05
H2_CI = Va_CI/(Va_CI + Ve_CI)

### Hybrid
Vg_Ch =  (78.19 - 19.55)/4
Ve_Ch = 19.55
H2_Ch = Vg_Ch/(Vg_Ch + Ve_Ch)


## Leaf width

### Inbred
Va_LI =  (508.3 - 42.4)/4
Ve_LI = 42.4
H2_LI = Va_LI/(Va_LI + Ve_LI)

### Hybrid
Vg_Lh =  (181.42 - 42.19)/4
Ve_Lh = 42.19
H2_Lh = Vg_Lh/(Vg_Lh + Ve_Lh)
```


```{r}
# Correlation between heterosis and heritability 
H2_Inb <- c(H2_YI, H2_CI, H2_LI)
H2_Hyb <- c(H2_Yh, H2_Ch, H2_Lh)

# Heterosis was shown in Flint's paper (Table 1)
AvgBPH_Het <- c(1.85, 0.66, 0.09)
Trait <- c("Plant Yield", "Cob Weight", "Leaf width")
HeH2 <- data.frame(Trait = Trait, H2_Inb = H2_Inb, H2_Hyb = H2_Hyb , AvgBPH_Het = AvgBPH_Het)

#Inbred
cor.test(HeH2$H2_Inb, HeH2$AvgBPH_Het, method = "pearson")
#Hybrid
cor.test(HeH2$H2_Hyb, HeH2$AvgBPH_Het, method = "pearson")

```


```{r}
# Visualization

Het <- data.frame(Trait = rep(HeH2$Trait, 2), H2 = c(H2_Inb, H2_Hyb), HI = rep(c("Inbred", "Hybrid"), each =3), AvgBPH_Het = rep(AvgBPH_Het, 2))
Het$H2 <- round(Het$H2, 4)

library(ggplot2)
ggplot(Het, aes(x=H2, y=AvgBPH_Het, color=HI, shape=HI)) +
  geom_point() + 
  geom_smooth(method=lm, aes(fill=HI))

```